stages:
  - build
# - test
  - quality

image: openjdk:24-jdk-oracle

cache:
  paths:
    - .m2/repository
  key:
    files:
      - pom.xml
  fallback_keys:
    - "maven-default"

before_script:
  - chmod +x mvnw

build-job:
  stage: build
  script:
    - ./mvnw compile -e
      -Dhttps.protocols=TLSv1.2
      -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
      -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
      -Dorg.slf4j.simpleLogger.showDateTime=true
      -Djava.awt.headless=true
      --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true

#unit-test-job:
#  stage: test
#  script:
#    - ./mvnw test
#      -Dhttps.protocols=TLSv1.2
#      -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
#      -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
#      -Dorg.slf4j.simpleLogger.showDateTime=true
#      -Djava.awt.headless=true
#      --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true


quality_job:
  stage: quality
  allow_failure: true
  image: docker:stable
  services:
    - name: docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - mkdir "codequality-results"
    - docker run
        --env CODECLIMATE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /tmp/cc:/tmp/cc
        codeclimate/codeclimate analyze -f json > gl-code-quality-report.json
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths:
      - gl-code-quality-report.json