### CREATE - administrateur
POST http://localhost:8080/api/administrateurs
Content-Type: application/json

{
  "username": "Amath",
  "email": "amath@ept.sn",
  "password": "amath123"
}

### READ - Lire un admin avec son id
GET http://localhost:8080/api/administrateurs/1

### READ - Lire un admin avec un id invalide
GET http://localhost:8080/api/administrateurs/99999

### READ - Lire tous les admins dans la base
GET http://localhost:8080/api/administrateurs

### UPDATE - Mettre à jour un admin
PUT http://localhost:8080/api/administrateurs/1
Content-Type: application/json

{
  "username": "Lamogo",
  "email": "lamogo@ept.sn",
  "password": "lamogo123"
}

### UPDATE - Mettre à jour un admin inexistant
PUT http://localhost:8080/api/administrateurs/99999
Content-Type: application/json

{
  "username": "Lamogo",
  "email": "lamogo@ept.sn",
  "password": "lamogo123"
}

### DELETE - Supprimer un admin
DELETE http://localhost:8080/api/administrateurs/2

### Recommandation

### CREATE - Créer une recommandation
POST http://localhost:8080/api/recommandations
Content-Type: application/json

{
  "nom_etablissement": "Gentle Academy",
  "email": "gentle@example.com",
  "telephone": "+000 74 023 20"
}

### READ - Lire une récommandation
GET http://localhost:8080/api/recommandations/1

### READ - Lire Toutes les recommandations
GET http://localhost:8080/api/recommandations

### UPDATE - Mettre à jour une recommandation
PUT http://localhost:8080/api/recommandations/1
Content-Type: application/json

{
  "nom_etablissement": "Ecole Supérieure Polytechnique",
  "email": "poly@example.com",
  "telephone": "73 239 23 23"
}

### DELETE - Supprimer une recommandations
DELETE http://localhost:8080/api/recommandations/4

###

### CREATE - Etablissement
POST http://localhost:8080/api/etablissement/
Content-Type: application/json

{
  "nom_etablissement": "Ecole Polytechnique de Thiès",
  "description": "Ecole d'ingénierie",
  "email": "ept@ept.sn",
  "telephone": "77 982 55 55",
  "statut": "PUBLIC",
  "site_web": "https://www.ept.edu.sn",
  "region": "Thiès",
  "ville": "Thès",
  "localisation": "14.7955479,-16.9695092"
}


### READ - Etablissement
GET http://localhost:8080/api/etablissement/

### READ - Etablissement
GET http://localhost:8080/api/etablissement/1

### UPDATE
PUT http://localhost:8080/api/etablissement/1
Content-Type: application/json

{
  "nom_etablissement": "Ecole Polytechnique de Thiès",
  "description": "Ecole d'ingénierie",
  "email": "ept@ept.sn",
  "telephone": "+221 76 223 61 60",
  "statut": "PUBLIC",
  "site_web": "https://www.ept.edu.sn",
  "region": "Thiès",
  "ville": "Thès",
  "localisation": "14.7955479,-16.9695092"
}

### DELETE
DELETE http://localhost:8080/api/etablissement/1

###

### CREATE - Formation pour un établissement
POST http://localhost:8080/api/etablissements/3/formations
Content-Type: application/json

{
  "nom": "Informatique",
  "description": "Formation de mois en Génie Informatique"
}

### READ - Lister les formations d'un établissement
GET http://localhost:8080/api/etablissements/3/formations

### READ - Lire une formation spécifique
GET http://localhost:8080/api/etablissements/3/formations/5

### UPDATE - Modifier une formation d'un établissement
PUT http://localhost:8080/api/etablissements/3/formations/5
Content-Type: application/json

{
  "nom": "Génie Industriel",
  "description": "Ingenierie Genie Industriel"
}

### DELETE - Supprimer une formation d'un établissement
DELETE http://localhost:8080/api/etablissements/3/formations/5

######### Informations publiées par les etablissements

###
POST http://localhost:8080/api/etablissements/2/infos
Content-Type: application/json

{
  "titre": "Inscription",
  "contenu": "Les inscriptions vont demarrer"
}

###
GET http://localhost:8080/api/etablissements/2/infos/5

###
GET http://localhost:8080/api/etablissements/2/infos

###
PUT http://localhost:8080/api/etablissements/2/infos/5
Content-Type: application/json

{
  "titre": "Inscription 2025/2026",
  "contenu": "Les inscriptions vont demarrer le lundi 17 octobre 2025 au niveau de la scolarité"
}

###
DELETE http://localhost:8080/api/etablissements/2/infos/5